"""create scans and findings tables

Revision ID: 262a084622ed
Revises: 
Create Date: 2026-05-30 15:35:48.530229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262a084622ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aws_account_id', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='scanstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('scans')
    # ### end Alembic commands ###
